/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Lab2.Dashboard2;
import Lab3.Dashboard3;
import java.awt.*;
import java.time.LocalDate;
import lab1grafico.Menu_de_Ejercicios;
import javax.swing.*;


/**
 *
 * @author Thebeast
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    int xx, xy;
    public Principal() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," Septiembre"
            ,"Octubre","Noviembre","Diciemrbre"};
        fecha.setText("Hoy es "+dia+" de "+meses[month - 1]+" de "+year);
        
        PresentacionP p1 = new PresentacionP();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        this.Solucion1.setVisible(false);
        Solucion1.setEnabled(false);
        this.Solucion2.setVisible(false);
        Solucion2.setEnabled(false);
        this.Solucion3.setVisible(false);
        Solucion3.setEnabled(false);
        this.Solucion4.setVisible(false);
        Solucion4.setEnabled(false);
        this.Solucion5.setVisible(false);
        Solucion5.setEnabled(false);
        this.Solucion6.setVisible(false);
        Solucion6.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        slogan = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Lab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Lab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Lab3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Lab4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        app_name = new javax.swing.JLabel();
        Lab5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Lab6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Presentacionl = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        content2 = new javax.swing.JPanel();
        Solucion1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Solucion2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Solucion3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Solucion4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Solucion5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Solucion6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(620, 380));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 620, 360));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(0, 0, 0));
        fecha.setText("Hoy es Sábado 28 de Abril de 2018");
        jPanel2.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 620, 80));

        jPanel3.setBackground(new java.awt.Color(0, 75, 50));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slogan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        slogan.setForeground(new java.awt.Color(255, 255, 255));
        slogan.setText("Facultad de Electrotecnia y Computación (F.E.C)");
        jPanel3.add(slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 300, 30));

        jPanel4.setBackground(new java.awt.Color(0, 75, 50));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("X");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 10, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 30, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 620, 80));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lab1.setBackground(new java.awt.Color(51, 51, 51));
        Lab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lab1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lab1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lab1MousePressed(evt);
            }
        });
        Lab1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LABORATORIO 1");
        Lab1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(Lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 40));

        Lab2.setBackground(new java.awt.Color(51, 51, 51));
        Lab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lab2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lab2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lab2MousePressed(evt);
            }
        });
        Lab2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LABORATORIO 2");
        Lab2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(Lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 210, 40));

        Lab3.setBackground(new java.awt.Color(51, 51, 51));
        Lab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lab3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lab3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lab3MousePressed(evt);
            }
        });
        Lab3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LABORATORIO 3");
        Lab3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(Lab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 210, 40));

        Lab4.setBackground(new java.awt.Color(51, 51, 51));
        Lab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lab4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lab4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lab4MousePressed(evt);
            }
        });
        Lab4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LABORATORIO 4");
        Lab4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(Lab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 210, 40));

        jPanel5.setBackground(new java.awt.Color(0, 51, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        app_name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        app_name.setForeground(new java.awt.Color(255, 255, 255));
        app_name.setText("INICIO");
        jPanel5.add(app_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 80));

        Lab5.setBackground(new java.awt.Color(51, 51, 51));
        Lab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lab5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lab5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lab5MousePressed(evt);
            }
        });
        Lab5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LABORATORIO 5");
        Lab5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(Lab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 210, 40));

        Lab6.setBackground(new java.awt.Color(51, 51, 51));
        Lab6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lab6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lab6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lab6MousePressed(evt);
            }
        });
        Lab6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LABORATORIO 6");
        Lab6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(Lab6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 210, 40));

        Presentacionl.setBackground(new java.awt.Color(51, 51, 51));
        Presentacionl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PresentacionlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PresentacionlMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PresentacionlMousePressed(evt);
            }
        });
        Presentacionl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PRESENTACION");
        Presentacionl.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(Presentacionl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 630));

        content2.setBackground(new java.awt.Color(255, 255, 255));
        content2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Solucion1.setBackground(new java.awt.Color(0, 75, 50));
        Solucion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Solucion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Solucion1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Solucion1MousePressed(evt);
            }
        });
        Solucion1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SOLUCIÓN");
        Solucion1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        content2.add(Solucion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 130, 40));

        Solucion2.setBackground(new java.awt.Color(0, 75, 50));
        Solucion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Solucion2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Solucion2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Solucion2MousePressed(evt);
            }
        });
        Solucion2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SOLUCIÓN");
        Solucion2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        content2.add(Solucion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 130, 40));

        Solucion3.setBackground(new java.awt.Color(0, 75, 50));
        Solucion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Solucion3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Solucion3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Solucion3MousePressed(evt);
            }
        });
        Solucion3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SOLUCIÓN");
        Solucion3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        content2.add(Solucion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 130, 40));

        Solucion4.setBackground(new java.awt.Color(0, 75, 50));
        Solucion4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Solucion4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Solucion4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Solucion4MousePressed(evt);
            }
        });
        Solucion4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SOLUCIÓN");
        Solucion4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        content2.add(Solucion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 130, 40));

        Solucion5.setBackground(new java.awt.Color(0, 75, 50));
        Solucion5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Solucion5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Solucion5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Solucion5MousePressed(evt);
            }
        });
        Solucion5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SOLUCIÓN");
        Solucion5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        content2.add(Solucion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 130, 40));

        Solucion6.setBackground(new java.awt.Color(0, 75, 50));
        Solucion6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Solucion6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Solucion6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Solucion6MousePressed(evt);
            }
        });
        Solucion6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SOLUCIÓN");
        Solucion6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        content2.add(Solucion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 130, 40));

        getContentPane().add(content2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 620, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // <editor-fold defaultstate="collapsed" desc="Botones de lab info">
    private void Lab1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab1MousePressed
        Lab1Info p1 = new Lab1Info();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        this.Solucion1.setVisible(true);
        Solucion1.setEnabled(true);
        this.Solucion2.setVisible(false);
        Solucion2.setEnabled(false);
        this.Solucion3.setVisible(false);
        Solucion3.setEnabled(false);
        this.Solucion4.setVisible(false);
        Solucion4.setEnabled(false);
        this.Solucion5.setVisible(false);
        Solucion5.setEnabled(false);
        this.Solucion6.setVisible(false);
        Solucion6.setEnabled(false);
    }//GEN-LAST:event_Lab1MousePressed

    private void Lab2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab2MousePressed
        Lab2Info p1 = new Lab2Info();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        this.Solucion1.setVisible(false);
        Solucion1.setEnabled(false);
        this.Solucion2.setVisible(true);
        Solucion2.setEnabled(true);
        this.Solucion3.setVisible(false);
        Solucion3.setEnabled(false);
        this.Solucion4.setVisible(false);
        Solucion4.setEnabled(false);
        this.Solucion5.setVisible(false);
        Solucion5.setEnabled(false);
        this.Solucion6.setVisible(false);
        Solucion6.setEnabled(false);
    }//GEN-LAST:event_Lab2MousePressed

    private void Lab3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab3MousePressed
        Lab3Info p1 = new Lab3Info();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        this.Solucion1.setVisible(false);
        Solucion1.setEnabled(false);
        this.Solucion2.setVisible(false);
        Solucion2.setEnabled(false);
        this.Solucion3.setVisible(true);
        Solucion3.setEnabled(true);
        this.Solucion4.setVisible(false);
        Solucion4.setEnabled(false);
        this.Solucion5.setVisible(false);
        Solucion5.setEnabled(false);
        this.Solucion6.setVisible(false);
        Solucion6.setEnabled(false);
    }//GEN-LAST:event_Lab3MousePressed

    private void Lab4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab4MousePressed
        Lab4Info p1 = new Lab4Info();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        this.Solucion1.setVisible(false);
        Solucion1.setEnabled(false);
        this.Solucion2.setVisible(false);
        Solucion2.setEnabled(false);
        this.Solucion3.setVisible(false);
        Solucion3.setEnabled(false);
        this.Solucion4.setVisible(true);
        Solucion4.setEnabled(true);
        this.Solucion5.setVisible(false);
        Solucion5.setEnabled(false);
        this.Solucion6.setVisible(false);
        Solucion6.setEnabled(false);
    }//GEN-LAST:event_Lab4MousePressed

    private void Lab5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab5MousePressed
        Lab5Info p1 = new Lab5Info();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        this.Solucion1.setVisible(false);
        Solucion1.setEnabled(false);
        this.Solucion2.setVisible(false);
        Solucion2.setEnabled(false);
        this.Solucion3.setVisible(false);
        Solucion3.setEnabled(false);
        this.Solucion4.setVisible(false);
        Solucion4.setEnabled(false);
        this.Solucion5.setVisible(true);
        Solucion5.setEnabled(true);
        this.Solucion6.setVisible(false);
        Solucion6.setEnabled(false);
    }//GEN-LAST:event_Lab5MousePressed

    private void Lab6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lab6MousePressed
    //</editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Botones de Solucion de Lab">
    private void Solucion1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion1MousePressed
        dispose();
        new Menu_de_Ejercicios().setVisible(true);
    }//GEN-LAST:event_Solucion1MousePressed

    private void Solucion2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion2MousePressed
        dispose();
        new Dashboard2().setVisible(true);   
    }//GEN-LAST:event_Solucion2MousePressed

    private void Solucion3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion3MousePressed
        dispose();
        new Dashboard3().setVisible(true);
    }//GEN-LAST:event_Solucion3MousePressed

    private void Solucion4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion4MousePressed
        dispose();
        new Lab4.Dashboard().setVisible(true);
    }//GEN-LAST:event_Solucion4MousePressed

    private void Solucion5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion5MousePressed
        dispose();
        new Lab5.Dashboard().setVisible(true);
    }//GEN-LAST:event_Solucion5MousePressed

    private void Solucion6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Solucion6MousePressed
//</editor-fold>
    private void PresentacionlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresentacionlMousePressed
        PresentacionP p1 = new PresentacionP();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        this.Solucion1.setVisible(false);
        Solucion1.setEnabled(false);
        this.Solucion2.setVisible(false);
        Solucion2.setEnabled(false);
        this.Solucion3.setVisible(false);
        Solucion3.setEnabled(false);
        this.Solucion4.setVisible(false);
        Solucion4.setEnabled(false);
        this.Solucion5.setVisible(false);
        Solucion5.setEnabled(false);
        this.Solucion6.setVisible(false);
        Solucion6.setEnabled(false);
    }//GEN-LAST:event_PresentacionlMousePressed
    // <editor-fold defaultstate="collapsed" desc="Animacion de botones y ">
    
    private void PresentacionlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresentacionlMouseEntered
        Presentacionl.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_PresentacionlMouseEntered

    private void PresentacionlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresentacionlMouseExited
        Presentacionl.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_PresentacionlMouseExited

    private void Solucion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion1MouseEntered
        Solucion1.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_Solucion1MouseEntered

    private void Solucion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion1MouseExited
        Solucion1.setBackground(new Color(0,75,50));
    }//GEN-LAST:event_Solucion1MouseExited

    private void Solucion2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion2MouseEntered
        Solucion2.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_Solucion2MouseEntered

    private void Solucion2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion2MouseExited
        Solucion2.setBackground(new Color(0,75,50));
    }//GEN-LAST:event_Solucion2MouseExited

    private void Solucion3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion3MouseEntered
        Solucion3.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_Solucion3MouseEntered

    private void Solucion3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion3MouseExited
        Solucion3.setBackground(new Color(0,75,50));
    }//GEN-LAST:event_Solucion3MouseExited

    private void Solucion4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion4MouseEntered
        Solucion4.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_Solucion4MouseEntered

    private void Solucion4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion4MouseExited
        Solucion4.setBackground(new Color(0,75,50));
    }//GEN-LAST:event_Solucion4MouseExited

    private void Solucion5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion5MouseEntered
        Solucion5.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_Solucion5MouseEntered

    private void Solucion5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion5MouseExited
        Solucion5.setBackground(new Color(0,75,50));
    }//GEN-LAST:event_Solucion5MouseExited

    private void Solucion6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion6MouseEntered
        Solucion6.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_Solucion6MouseEntered

    private void Solucion6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion6MouseExited
        Solucion6.setBackground(new Color(0,75,50));
    }//GEN-LAST:event_Solucion6MouseExited

    private void Lab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab1MouseEntered
        Lab1.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_Lab1MouseEntered

    private void Lab1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab1MouseExited
        Lab1.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_Lab1MouseExited

    private void Lab2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab2MouseEntered
        Lab2.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_Lab2MouseEntered

    private void Lab2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab2MouseExited
        Lab2.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_Lab2MouseExited

    private void Lab3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab3MouseEntered
        Lab3.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_Lab3MouseEntered

    private void Lab3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab3MouseExited
        Lab3.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_Lab3MouseExited

    private void Lab4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab4MouseEntered
        Lab4.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_Lab4MouseEntered

    private void Lab4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab4MouseExited
        Lab4.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_Lab4MouseExited

    private void Lab5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab5MouseEntered
        Lab5.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_Lab5MouseEntered

    private void Lab5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab5MouseExited
        Lab5.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_Lab5MouseExited

    private void Lab6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab6MouseEntered
        Lab6.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_Lab6MouseEntered

    private void Lab6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab6MouseExited
        Lab6.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_Lab6MouseExited

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        System.exit(0);
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        jPanel4.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        jPanel4.setBackground(new Color(0,75,50));
    }//GEN-LAST:event_jPanel4MouseExited
    //</editor-fold>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Lab1;
    private javax.swing.JPanel Lab2;
    private javax.swing.JPanel Lab3;
    private javax.swing.JPanel Lab4;
    private javax.swing.JPanel Lab5;
    private javax.swing.JPanel Lab6;
    private javax.swing.JPanel Presentacionl;
    private javax.swing.JPanel Solucion1;
    private javax.swing.JPanel Solucion2;
    private javax.swing.JPanel Solucion3;
    private javax.swing.JPanel Solucion4;
    private javax.swing.JPanel Solucion5;
    private javax.swing.JPanel Solucion6;
    private javax.swing.JLabel app_name;
    private javax.swing.JPanel content;
    private javax.swing.JPanel content2;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel slogan;
    // End of variables declaration//GEN-END:variables
}
