/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Lab2.Dashboard2;
import Lab3.Dashboard3;
import java.awt.BorderLayout;
import java.time.LocalDate;
import lab1grafico.Menu_de_Ejercicios;


/**
 *
 * @author Thebeast
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," Septiembre"
            ,"Octubre","Noviembre","Diciemrbre"};
        fecha.setText("Hoy es "+dia+" de "+meses[month - 1]+" de "+year);
        
        PresentacionP p1 = new PresentacionP();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        Laboratorios.setEnabled(true);
        this.LAB1.setVisible(false);
        this.LAB2.setVisible(false);
        this.LAB3.setVisible(false);
        this.LAB4.setVisible(false);
        this.LAB5.setVisible(false);
        this.LAB6.setVisible(false);
        this.Guia1.setVisible(false);
        this.Solucion1.setVisible(false);
        Guia1.setEnabled(false);
        Solucion1.setEnabled(false);
        this.Guia2.setVisible(false);
        this.Solucion2.setVisible(false);
        Guia2.setEnabled(false);
        Solucion2.setEnabled(false);
        this.Guia3.setVisible(false);
        this.Solucion3.setVisible(false);
        Guia3.setEnabled(false);
        Solucion3.setEnabled(false);
        this.Guia4.setVisible(false);
        this.Solucion4.setVisible(false);
        Guia4.setEnabled(false);
        Solucion4.setEnabled(false);
        this.Guia5.setVisible(false);
        this.Solucion5.setVisible(false);
        Guia5.setEnabled(false);
        Solucion5.setEnabled(false);
        this.Guia6.setVisible(false);
        this.Solucion6.setVisible(false);
        Guia6.setEnabled(false);
        Solucion6.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        slogan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        app_name = new javax.swing.JLabel();
        LAB6 = new javax.swing.JButton();
        Presentacion = new javax.swing.JButton();
        LAB1 = new javax.swing.JButton();
        LAB2 = new javax.swing.JButton();
        LAB3 = new javax.swing.JButton();
        LAB4 = new javax.swing.JButton();
        LAB5 = new javax.swing.JButton();
        content2 = new javax.swing.JPanel();
        Solucion1 = new javax.swing.JButton();
        Guia1 = new javax.swing.JButton();
        Guia2 = new javax.swing.JButton();
        Solucion2 = new javax.swing.JButton();
        Guia3 = new javax.swing.JButton();
        Solucion3 = new javax.swing.JButton();
        Guia4 = new javax.swing.JButton();
        Solucion4 = new javax.swing.JButton();
        Guia5 = new javax.swing.JButton();
        Solucion5 = new javax.swing.JButton();
        Solucion6 = new javax.swing.JButton();
        Guia6 = new javax.swing.JButton();
        Laboratorios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(620, 380));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 620, 360));

        jPanel2.setBackground(new java.awt.Color(25, 118, 210));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Hoy es Sábado 28 de Abril de 2018");
        jPanel2.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 620, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slogan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        slogan.setText("Facultad de Electrotecnia y Computación (F.E.C)");
        jPanel3.add(slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 300, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 620, 80));

        jPanel1.setBackground(new java.awt.Color(13, 71, 161));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        app_name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        app_name.setForeground(new java.awt.Color(255, 255, 255));
        app_name.setText("INICIO");
        jPanel1.add(app_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        LAB6.setBackground(new java.awt.Color(21, 101, 192));
        LAB6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LAB6.setForeground(new java.awt.Color(255, 255, 255));
        LAB6.setText("LABORATORIO 6");
        LAB6.setBorder(null);
        jPanel1.add(LAB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 210, 50));

        Presentacion.setBackground(new java.awt.Color(21, 101, 192));
        Presentacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Presentacion.setForeground(new java.awt.Color(255, 255, 255));
        Presentacion.setText("PRESENTACION");
        Presentacion.setBorder(null);
        Presentacion.setBorderPainted(false);
        Presentacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PresentacionMousePressed(evt);
            }
        });
        jPanel1.add(Presentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 50));

        LAB1.setBackground(new java.awt.Color(21, 101, 192));
        LAB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LAB1.setForeground(new java.awt.Color(255, 255, 255));
        LAB1.setText("LABORATORIO 1");
        LAB1.setBorder(null);
        LAB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LAB1MousePressed(evt);
            }
        });
        jPanel1.add(LAB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 50));

        LAB2.setBackground(new java.awt.Color(21, 101, 192));
        LAB2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LAB2.setForeground(new java.awt.Color(255, 255, 255));
        LAB2.setText("LABORATORIO 2");
        LAB2.setBorder(null);
        LAB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LAB2MousePressed(evt);
            }
        });
        jPanel1.add(LAB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 210, 50));

        LAB3.setBackground(new java.awt.Color(21, 101, 192));
        LAB3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LAB3.setForeground(new java.awt.Color(255, 255, 255));
        LAB3.setText("LABORATORIO 3");
        LAB3.setBorder(null);
        LAB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LAB3MousePressed(evt);
            }
        });
        jPanel1.add(LAB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 210, 50));

        LAB4.setBackground(new java.awt.Color(21, 101, 192));
        LAB4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LAB4.setForeground(new java.awt.Color(255, 255, 255));
        LAB4.setText("LABORATORIO 4");
        LAB4.setBorder(null);
        LAB4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LAB4MousePressed(evt);
            }
        });
        jPanel1.add(LAB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 210, 50));

        LAB5.setBackground(new java.awt.Color(21, 101, 192));
        LAB5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LAB5.setForeground(new java.awt.Color(255, 255, 255));
        LAB5.setText("LABORATORIO 5");
        LAB5.setBorder(null);
        LAB5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LAB5MousePressed(evt);
            }
        });
        jPanel1.add(LAB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 210, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 630));

        content2.setBackground(new java.awt.Color(255, 255, 255));
        content2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Solucion1.setBackground(new java.awt.Color(21, 101, 192));
        Solucion1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Solucion1.setForeground(new java.awt.Color(255, 255, 255));
        Solucion1.setText("SOLUCION");
        Solucion1.setBorder(null);
        Solucion1.setEnabled(false);
        Solucion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Solucion1MousePressed(evt);
            }
        });
        content2.add(Solucion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 130, 40));

        Guia1.setBackground(new java.awt.Color(21, 101, 192));
        Guia1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Guia1.setForeground(new java.awt.Color(255, 255, 255));
        Guia1.setText("Guia");
        Guia1.setBorder(null);
        Guia1.setEnabled(false);
        content2.add(Guia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, 40));

        Guia2.setBackground(new java.awt.Color(21, 101, 192));
        Guia2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Guia2.setForeground(new java.awt.Color(255, 255, 255));
        Guia2.setText("Guia");
        Guia2.setBorder(null);
        Guia2.setEnabled(false);
        content2.add(Guia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, 40));

        Solucion2.setBackground(new java.awt.Color(21, 101, 192));
        Solucion2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Solucion2.setForeground(new java.awt.Color(255, 255, 255));
        Solucion2.setText("SOLUCION");
        Solucion2.setBorder(null);
        Solucion2.setEnabled(false);
        Solucion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Solucion2MousePressed(evt);
            }
        });
        content2.add(Solucion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 130, 40));

        Guia3.setBackground(new java.awt.Color(21, 101, 192));
        Guia3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Guia3.setForeground(new java.awt.Color(255, 255, 255));
        Guia3.setText("Guia");
        Guia3.setBorder(null);
        Guia3.setEnabled(false);
        content2.add(Guia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, 40));

        Solucion3.setBackground(new java.awt.Color(21, 101, 192));
        Solucion3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Solucion3.setForeground(new java.awt.Color(255, 255, 255));
        Solucion3.setText("SOLUCION");
        Solucion3.setBorder(null);
        Solucion3.setEnabled(false);
        Solucion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Solucion3MousePressed(evt);
            }
        });
        content2.add(Solucion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 130, 40));

        Guia4.setBackground(new java.awt.Color(21, 101, 192));
        Guia4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Guia4.setForeground(new java.awt.Color(255, 255, 255));
        Guia4.setText("Guia");
        Guia4.setBorder(null);
        Guia4.setEnabled(false);
        content2.add(Guia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, 40));

        Solucion4.setBackground(new java.awt.Color(21, 101, 192));
        Solucion4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Solucion4.setForeground(new java.awt.Color(255, 255, 255));
        Solucion4.setText("SOLUCION");
        Solucion4.setBorder(null);
        Solucion4.setEnabled(false);
        Solucion4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Solucion4MousePressed(evt);
            }
        });
        content2.add(Solucion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 130, 40));

        Guia5.setBackground(new java.awt.Color(21, 101, 192));
        Guia5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Guia5.setForeground(new java.awt.Color(255, 255, 255));
        Guia5.setText("Guia");
        Guia5.setBorder(null);
        Guia5.setEnabled(false);
        content2.add(Guia5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, 40));

        Solucion5.setBackground(new java.awt.Color(21, 101, 192));
        Solucion5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Solucion5.setForeground(new java.awt.Color(255, 255, 255));
        Solucion5.setText("SOLUCION");
        Solucion5.setBorder(null);
        Solucion5.setEnabled(false);
        Solucion5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Solucion5MousePressed(evt);
            }
        });
        content2.add(Solucion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 130, 40));

        Solucion6.setBackground(new java.awt.Color(21, 101, 192));
        Solucion6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Solucion6.setForeground(new java.awt.Color(255, 255, 255));
        Solucion6.setText("SOLUCION");
        Solucion6.setBorder(null);
        Solucion6.setEnabled(false);
        Solucion6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Solucion6MousePressed(evt);
            }
        });
        content2.add(Solucion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 130, 40));

        Guia6.setBackground(new java.awt.Color(21, 101, 192));
        Guia6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Guia6.setForeground(new java.awt.Color(255, 255, 255));
        Guia6.setText("Guia");
        Guia6.setBorder(null);
        Guia6.setEnabled(false);
        content2.add(Guia6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, 40));

        Laboratorios.setBackground(new java.awt.Color(21, 101, 192));
        Laboratorios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Laboratorios.setForeground(new java.awt.Color(255, 255, 255));
        Laboratorios.setText("LABORATORIOS");
        Laboratorios.setBorder(null);
        Laboratorios.setEnabled(false);
        Laboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LaboratoriosMousePressed(evt);
            }
        });
        content2.add(Laboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 130, 40));

        getContentPane().add(content2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 620, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PresentacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PresentacionMousePressed
        PresentacionP p1 = new PresentacionP();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        this.LAB1.setVisible(false);
        this.LAB2.setVisible(false);
        this.LAB3.setVisible(false);
        this.LAB4.setVisible(false);
        this.LAB5.setVisible(false);
        this.LAB6.setVisible(false);
        this.Laboratorios.setVisible(true);
        Laboratorios.setEnabled(true);
        this.Guia1.setVisible(false);
        this.Solucion1.setVisible(false);
        Guia1.setEnabled(false);
        Solucion1.setEnabled(false);
        this.Guia2.setVisible(false);
        this.Solucion2.setVisible(false);
        Guia2.setEnabled(false);
        Solucion2.setEnabled(false);
        this.Guia3.setVisible(false);
        this.Solucion3.setVisible(false);
        Guia3.setEnabled(false);
        Solucion3.setEnabled(false);
        this.Guia4.setVisible(false);
        this.Solucion4.setVisible(false);
        Guia4.setEnabled(false);
        Solucion4.setEnabled(false);
        this.Guia5.setVisible(false);
        this.Solucion5.setVisible(false);
        Guia5.setEnabled(false);
        Solucion5.setEnabled(false);
        this.Guia6.setVisible(false);
        this.Solucion6.setVisible(false);
        Guia6.setEnabled(false);
        Solucion6.setEnabled(false);
    }//GEN-LAST:event_PresentacionMousePressed

    private void LAB1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAB1MousePressed
        Lab1Info p1 = new Lab1Info();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        this.Laboratorios.setVisible(false);
        Laboratorios.setEnabled(false);
        this.Guia1.setVisible(true);
        this.Solucion1.setVisible(true);
        Guia1.setEnabled(true);
        Solucion1.setEnabled(true);
        this.Guia2.setVisible(false);
        this.Solucion2.setVisible(false);
        Guia2.setEnabled(false);
        Solucion2.setEnabled(false);
        this.Guia3.setVisible(false);
        this.Solucion3.setVisible(false);
        Guia3.setEnabled(false);
        Solucion3.setEnabled(false);
        this.Guia4.setVisible(false);
        this.Solucion4.setVisible(false);
        Guia4.setEnabled(false);
        Solucion4.setEnabled(false);
        this.Guia5.setVisible(false);
        this.Solucion5.setVisible(false);
        Guia5.setEnabled(false);
        Solucion5.setEnabled(false);
        this.Guia6.setVisible(false);
        this.Solucion6.setVisible(false);
        Guia6.setEnabled(false);
        Solucion6.setEnabled(false);
    }//GEN-LAST:event_LAB1MousePressed

    private void LAB2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAB2MousePressed
        Lab2Info p1 = new Lab2Info();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        this.Laboratorios.setVisible(false);
        Laboratorios.setEnabled(false);
        this.Guia1.setVisible(false);
        this.Solucion1.setVisible(false);
        Guia1.setEnabled(false);
        Solucion1.setEnabled(false);
        this.Guia2.setVisible(true);
        this.Solucion2.setVisible(true);
        Guia2.setEnabled(true);
        Solucion2.setEnabled(true);
        this.Guia3.setVisible(false);
        this.Solucion3.setVisible(false);
        Guia3.setEnabled(false);
        Solucion3.setEnabled(false);
        this.Guia4.setVisible(false);
        this.Solucion4.setVisible(false);
        Guia4.setEnabled(false);
        Solucion4.setEnabled(false);
        this.Guia5.setVisible(false);
        this.Solucion5.setVisible(false);
        Guia5.setEnabled(false);
        Solucion5.setEnabled(false);
        this.Guia6.setVisible(false);
        this.Solucion6.setVisible(false);
        Guia6.setEnabled(false);
        Solucion6.setEnabled(false);
    }//GEN-LAST:event_LAB2MousePressed

    private void Solucion1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion1MousePressed
        dispose();
        new Menu_de_Ejercicios().setVisible(true);
    }//GEN-LAST:event_Solucion1MousePressed

    private void Solucion2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion2MousePressed
        dispose();
        new Dashboard2().setVisible(true);        
    }//GEN-LAST:event_Solucion2MousePressed

    private void Solucion3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion3MousePressed
        dispose();
        new Dashboard3().setVisible(true);
    }//GEN-LAST:event_Solucion3MousePressed

    private void Solucion4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion4MousePressed
        dispose();
        new Lab4.Dashboard().setVisible(true);
    }//GEN-LAST:event_Solucion4MousePressed

    private void Solucion5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion5MousePressed
        dispose();
        new Lab5.Dashboard().setVisible(true);
    }//GEN-LAST:event_Solucion5MousePressed

    private void Solucion6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Solucion6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Solucion6MousePressed

    private void LAB3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAB3MousePressed
        Lab3Info p1 = new Lab3Info();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        this.Laboratorios.setVisible(false);
        Laboratorios.setEnabled(false);
        this.Guia1.setVisible(false);
        this.Solucion1.setVisible(false);
        Guia1.setEnabled(false);
        Solucion1.setEnabled(false);
        this.Guia2.setVisible(false);
        this.Solucion2.setVisible(false);
        Guia2.setEnabled(false);
        Solucion2.setEnabled(false);
        this.Guia3.setVisible(true);
        this.Solucion3.setVisible(true);
        Guia3.setEnabled(true);
        Solucion3.setEnabled(true);
        this.Guia4.setVisible(false);
        this.Solucion4.setVisible(false);
        Guia4.setEnabled(false);
        Solucion4.setEnabled(false);
        this.Guia5.setVisible(false);
        this.Solucion5.setVisible(false);
        Guia5.setEnabled(false);
        Solucion5.setEnabled(false);
        this.Guia6.setVisible(false);
        this.Solucion6.setVisible(false);
        Guia6.setEnabled(false);
        Solucion6.setEnabled(false);
    }//GEN-LAST:event_LAB3MousePressed

    private void LAB4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAB4MousePressed
        Lab4Info p1 = new Lab4Info();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        this.Laboratorios.setVisible(false);
        Laboratorios.setEnabled(false);
        this.Guia1.setVisible(false);
        this.Solucion1.setVisible(false);
        Guia1.setEnabled(false);
        Solucion1.setEnabled(false);
        this.Guia2.setVisible(false);
        this.Solucion2.setVisible(false);
        Guia2.setEnabled(false);
        Solucion2.setEnabled(false);
        this.Guia3.setVisible(false);
        this.Solucion3.setVisible(false);
        Guia3.setEnabled(false);
        Solucion3.setEnabled(false);
        this.Guia4.setVisible(true);
        this.Solucion4.setVisible(true);
        Guia4.setEnabled(true);
        Solucion4.setEnabled(true);
        this.Guia5.setVisible(false);
        this.Solucion5.setVisible(false);
        Guia5.setEnabled(false);
        Solucion5.setEnabled(false);
        this.Guia6.setVisible(false);
        this.Solucion6.setVisible(false);
        Guia6.setEnabled(false);
        Solucion6.setEnabled(false);
    }//GEN-LAST:event_LAB4MousePressed

    private void LAB5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAB5MousePressed
        Lab5Info p1 = new Lab5Info();
        p1.setSize(620, 470);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        this.Laboratorios.setVisible(false);
        Laboratorios.setEnabled(false);
        this.Guia1.setVisible(false);
        this.Solucion1.setVisible(false);
        Guia1.setEnabled(false);
        Solucion1.setEnabled(false);
        this.Guia2.setVisible(false);
        this.Solucion2.setVisible(false);
        Guia2.setEnabled(false);
        Solucion2.setEnabled(false);
        this.Guia3.setVisible(false);
        this.Solucion3.setVisible(false);
        Guia3.setEnabled(false);
        Solucion3.setEnabled(false);
        this.Guia4.setVisible(false);
        this.Solucion4.setVisible(false);
        Guia4.setEnabled(false);
        Solucion4.setEnabled(false);
        this.Guia5.setVisible(true);
        this.Solucion5.setVisible(true);
        Guia5.setEnabled(true);
        Solucion5.setEnabled(true);
        this.Guia6.setVisible(false);
        this.Solucion6.setVisible(false);
        Guia6.setEnabled(false);
        Solucion6.setEnabled(false);
    }//GEN-LAST:event_LAB5MousePressed

    private void LaboratoriosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaboratoriosMousePressed
        this.LAB1.setVisible(true);
        this.LAB2.setVisible(true);
        this.LAB3.setVisible(true);
        this.LAB4.setVisible(true);
        this.LAB5.setVisible(true);
        this.LAB6.setVisible(true);
    }//GEN-LAST:event_LaboratoriosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guia1;
    private javax.swing.JButton Guia2;
    private javax.swing.JButton Guia3;
    private javax.swing.JButton Guia4;
    private javax.swing.JButton Guia5;
    private javax.swing.JButton Guia6;
    private javax.swing.JButton LAB1;
    private javax.swing.JButton LAB2;
    private javax.swing.JButton LAB3;
    private javax.swing.JButton LAB4;
    private javax.swing.JButton LAB5;
    private javax.swing.JButton LAB6;
    private javax.swing.JButton Laboratorios;
    private javax.swing.JButton Presentacion;
    private javax.swing.JButton Solucion1;
    private javax.swing.JButton Solucion2;
    private javax.swing.JButton Solucion3;
    private javax.swing.JButton Solucion4;
    private javax.swing.JButton Solucion5;
    private javax.swing.JButton Solucion6;
    private javax.swing.JLabel app_name;
    private javax.swing.JPanel content;
    private javax.swing.JPanel content2;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel slogan;
    // End of variables declaration//GEN-END:variables
}
