/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Lab4.Notacion;

import Lab4.*;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author david
 */
public class NotacionPolaca extends javax.swing.JPanel {

    /**
     * Creates new form NotacionPolaca
     */
    public NotacionPolaca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        infija = new javax.swing.JTextField();
        mostrarPrefija = new javax.swing.JLabel();
        mostrarInfija = new javax.swing.JLabel();
        button_Añadir = new javax.swing.JPanel();
        Lb_TextAñadir = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Introduce una notación infija para convertirla a prefija y postfija:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 560, 20));

        infija.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        add(infija, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 234, -1));

        mostrarPrefija.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        mostrarPrefija.setText(" ");
        add(mostrarPrefija, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 371, -1));

        mostrarInfija.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        mostrarInfija.setText(" ");
        add(mostrarInfija, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 371, -1));

        button_Añadir.setBackground(new java.awt.Color(0, 75, 50));
        button_Añadir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button_Añadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_AñadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_AñadirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_AñadirMousePressed(evt);
            }
        });
        button_Añadir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lb_TextAñadir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lb_TextAñadir.setForeground(new java.awt.Color(255, 255, 255));
        Lb_TextAñadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_TextAñadir.setText("Convertir");
        button_Añadir.add(Lb_TextAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        add(button_Añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 260, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void button_AñadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_AñadirMouseEntered
        setColor(button_Añadir);
    }//GEN-LAST:event_button_AñadirMouseEntered

    private void button_AñadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_AñadirMouseExited
        resetColor(button_Añadir);
    }//GEN-LAST:event_button_AñadirMouseExited
    //Convertir
    private void button_AñadirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_AñadirMousePressed
        if(infija.getText().length() > 0)
        {
            conversor.convertir(infija.getText(), mostrarPrefija,mostrarInfija);
        }
    }//GEN-LAST:event_button_AñadirMousePressed
//Colores
void setColor(JPanel panel){
    panel.setBackground(new Color(21,101,192));
}
void resetColor(JPanel panel){
    panel.setBackground(new Color(18,90,173));
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lb_TextAñadir;
    private javax.swing.JPanel button_Añadir;
    private javax.swing.JTextField infija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mostrarInfija;
    private javax.swing.JLabel mostrarPrefija;
    // End of variables declaration//GEN-END:variables
}
