package Lab3;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JPanel;
import Principal.Principal;
public class Dashboard extends javax.swing.JFrame {
    //Creando variables de control
    //Ubicacion de la ventana
    int xMouse;
    int yMouse;
    int unico = 0;
    /**
     * Creates new form Dashboard
     */
    //Iniciando componentes y cargando el menu principal
    
    
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
        
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," Septiembre"
            ,"Octubre","Noviembre","Diciemrbre"};
        fecha.setText("Hoy es "+dia+" de "+meses[month - 1]+" de "+year);
        
        Principal3 p1 = new Principal3();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        btn_prin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_Ejercicio2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_Ejercicio3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_Espacios = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_Ejercicio1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_Ejercicio5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_Ejercicio6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        app_name = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Regresarp = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        Title = new javax.swing.JPanel();
        red_squr = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Background.setBackground(new java.awt.Color(0, 75, 50));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(51, 51, 51));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_prin.setBackground(new java.awt.Color(51, 51, 51));
        btn_prin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_prin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_prinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_prinMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_prinMousePressed(evt);
            }
        });
        btn_prin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home-outline.png"))); // NOI18N
        btn_prin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Principal");
        btn_prin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_prin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 270, 50));

        btn_Ejercicio2.setBackground(new java.awt.Color(51, 51, 51));
        btn_Ejercicio2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Ejercicio2.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_Ejercicio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Ejercicio2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Ejercicio2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Ejercicio2MousePressed(evt);
            }
        });
        btn_Ejercicio2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendar-multiple-check.png"))); // NOI18N
        btn_Ejercicio2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ejercicio 2");
        btn_Ejercicio2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_Ejercicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        btn_Ejercicio3.setBackground(new java.awt.Color(51, 51, 51));
        btn_Ejercicio3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Ejercicio3.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_Ejercicio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Ejercicio3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Ejercicio3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Ejercicio3MousePressed(evt);
            }
        });
        btn_Ejercicio3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendar-plus.png"))); // NOI18N
        btn_Ejercicio3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ejercicio 3");
        btn_Ejercicio3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_Ejercicio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        btn_Espacios.setBackground(new java.awt.Color(51, 51, 51));
        btn_Espacios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Espacios.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_Espacios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EspaciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EspaciosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_EspaciosMousePressed(evt);
            }
        });
        btn_Espacios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendar-multiple-check.png"))); // NOI18N
        btn_Espacios.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ejercicio 4");
        btn_Espacios.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_Espacios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        btn_Ejercicio1.setBackground(new java.awt.Color(51, 51, 51));
        btn_Ejercicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Ejercicio1.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_Ejercicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Ejercicio1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Ejercicio1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Ejercicio1MousePressed(evt);
            }
        });
        btn_Ejercicio1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendar-plus.png"))); // NOI18N
        btn_Ejercicio1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ejercicio 1");
        btn_Ejercicio1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, 30));

        Menu.add(btn_Ejercicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        btn_Ejercicio5.setBackground(new java.awt.Color(51, 51, 51));
        btn_Ejercicio5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Ejercicio5.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_Ejercicio5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Ejercicio5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Ejercicio5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Ejercicio5MousePressed(evt);
            }
        });
        btn_Ejercicio5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendar-multiple-check.png"))); // NOI18N
        btn_Ejercicio5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ejercicio 5");
        btn_Ejercicio5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_Ejercicio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        btn_Ejercicio6.setBackground(new java.awt.Color(51, 51, 51));
        btn_Ejercicio6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Ejercicio6.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_Ejercicio6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Ejercicio6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Ejercicio6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Ejercicio6MousePressed(evt);
            }
        });
        btn_Ejercicio6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendar-multiple-check.png"))); // NOI18N
        btn_Ejercicio6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ejercicio 6");
        btn_Ejercicio6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_Ejercicio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        app_name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        app_name.setForeground(new java.awt.Color(255, 255, 255));
        app_name.setText("LABORATORIO 3");
        jPanel1.add(app_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 190, 20));

        Menu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 60));

        Regresarp.setBackground(new java.awt.Color(51, 51, 51));
        Regresarp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegresarpMousePressed(evt);
            }
        });
        Regresarp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Regresar");
        Regresarp.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        Menu.add(Regresarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 270, 50));

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 640));

        Header.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ejercicios de Recursividad");

        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(0, 0, 0));
        fecha.setText("Hoy es Sábado 28 de Abril de 2018");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(fecha))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 750, 150));

        Title.setBackground(new java.awt.Color(0, 75, 50));
        Title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleMouseDragged(evt);
            }
        });
        Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitleMousePressed(evt);
            }
        });

        red_squr.setBackground(new java.awt.Color(0, 75, 50));
        red_squr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        red_squr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                red_squrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                red_squrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                red_squrMousePressed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout red_squrLayout = new javax.swing.GroupLayout(red_squr);
        red_squr.setLayout(red_squrLayout);
        red_squrLayout.setHorizontalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        red_squrLayout.setVerticalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleLayout.createSequentialGroup()
                .addGap(0, 984, Short.MAX_VALUE)
                .addComponent(red_squr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(red_squr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Background.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        slogan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        slogan.setForeground(new java.awt.Color(255, 255, 255));
        slogan.setText("Facultad de Electrotecnia y Computación (F.E.C)");
        Background.add(slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 300, 30));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Activar_color(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        Background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 750, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated
//Arrastrar ventana
    private void TitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_TitleMouseDragged

    private void TitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_TitleMousePressed
// Funciones de los Botones
    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void btn_prinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prinMousePressed
        setColor(btn_prin);
        resetColor(btn_Ejercicio1);
        if(unico > 0)
        {
            resetColor(btn_Ejercicio2);
            resetColor(btn_Ejercicio3);
            resetColor(btn_Espacios);
            resetColor(btn_Ejercicio6);
            resetColor(btn_Ejercicio5);
        }
        // Abrir sección
        Principal3 p1 = new Principal3();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_prinMousePressed

    private void btn_Ejercicio1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio1MousePressed
        
        resetColor(btn_prin);
        setColor(btn_Ejercicio1);
        if(unico > 0)
        {
            resetColor(btn_Ejercicio2);
            resetColor(btn_Ejercicio3);
            resetColor(btn_Espacios);
            resetColor(btn_Ejercicio6);
            resetColor(btn_Ejercicio5);
        }
        Invertir_Arreglo arreglo = new Invertir_Arreglo();
        //Arreglo en global;
        arreglo.setSize(750, 430);
        arreglo.setLocation(0,0);
        content.removeAll();
        content.add(arreglo, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btn_Ejercicio1MousePressed

    private void btn_Ejercicio2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio2MousePressed

        resetColor(btn_prin);
        resetColor(btn_Ejercicio1);
        setColor(btn_Ejercicio2);
        resetColor(btn_Ejercicio3);
        resetColor(btn_Espacios);
        resetColor(btn_Ejercicio6);
        resetColor(btn_Ejercicio5);
        // Abrir sección
        palabra p1 = new palabra();
        p1.setSize(750, 430);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }//GEN-LAST:event_btn_Ejercicio2MousePressed

    private void btn_Ejercicio3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio3MousePressed

       
        resetColor(btn_prin);
        resetColor(btn_Ejercicio1);
        resetColor(btn_Ejercicio2);
        setColor(btn_Ejercicio3);
        resetColor(btn_Espacios);
        resetColor(btn_Ejercicio6);
        resetColor(btn_Ejercicio5);
        // Abrir sección
        Producto_Arreglo p1 = new Producto_Arreglo();
        p1.setSize(750, 430);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
 
    }//GEN-LAST:event_btn_Ejercicio3MousePressed

    private void btn_EspaciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EspaciosMousePressed

       
        resetColor(btn_prin);
        resetColor(btn_Ejercicio1);
        resetColor(btn_Ejercicio2);
        resetColor(btn_Ejercicio3);
        setColor(btn_Espacios);
        resetColor(btn_Ejercicio6);
        resetColor(btn_Ejercicio5);
        // Abrir sección
        Espacios p1 = new Espacios();
        p1.setSize(750, 430);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
       
    }//GEN-LAST:event_btn_EspaciosMousePressed

    private void red_squrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMousePressed
        System.exit(0);
    }//GEN-LAST:event_red_squrMousePressed

//Aniamcion de Botones para estilizarlos
    private void btn_Ejercicio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio1MouseEntered
        if(btn_Ejercicio1.getBackground().getRGB() == -15574355)
            setColor(btn_Ejercicio1);
    }//GEN-LAST:event_btn_Ejercicio1MouseEntered

    private void btn_Ejercicio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio1MouseExited
        if(btn_prin.getBackground().getRGB() == -15374912 || 
           btn_Ejercicio2.getBackground().getRGB() == -15374912 || btn_Ejercicio3.getBackground().getRGB() == -15374912
           || btn_Espacios.getBackground().getRGB() == -15374912 || btn_Ejercicio5.getBackground().getRGB() == -15374912
           || btn_Ejercicio6.getBackground().getRGB() == -15374912 )
            {
                resetColor(btn_Ejercicio1);
            }
    }//GEN-LAST:event_btn_Ejercicio1MouseExited

    private void btn_prinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prinMouseEntered
        if(btn_prin.getBackground().getRGB() == -15574355)
            setColor(btn_prin);
    }//GEN-LAST:event_btn_prinMouseEntered

    private void btn_prinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prinMouseExited
        if(btn_Ejercicio1.getBackground().getRGB() == -15374912
           || btn_Ejercicio2.getBackground().getRGB() == -15374912 || btn_Ejercicio3.getBackground().getRGB() == -15374912
           || btn_Espacios.getBackground().getRGB() == -15374912 || btn_Ejercicio5.getBackground().getRGB() == -15374912
           || btn_Ejercicio6.getBackground().getRGB() == -15374912)
            {
                resetColor(btn_prin);
            }
    }//GEN-LAST:event_btn_prinMouseExited

    private void btn_Ejercicio2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio2MouseEntered
        if(btn_Ejercicio2.getBackground().getRGB() == -15574355)
            setColor(btn_Ejercicio2);
    }//GEN-LAST:event_btn_Ejercicio2MouseEntered

    private void btn_Ejercicio2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio2MouseExited
        if((btn_prin.getBackground().getRGB() == -15374912 || btn_Ejercicio1.getBackground().getRGB() == -15374912
         || btn_Ejercicio3.getBackground().getRGB() == -15374912
           || btn_Espacios.getBackground().getRGB() == -15374912 || btn_Ejercicio5.getBackground().getRGB() == -15374912
           || btn_Ejercicio6.getBackground().getRGB() == -15374912) && btn_Ejercicio2.getBackground().getRGB() != -6710887)
            {
                resetColor(btn_Ejercicio2);
            }
    }//GEN-LAST:event_btn_Ejercicio2MouseExited

    private void btn_Ejercicio3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio3MouseEntered
      if(btn_Ejercicio3.getBackground().getRGB() == -15574355)
            setColor(btn_Ejercicio3);
    }//GEN-LAST:event_btn_Ejercicio3MouseEntered

    private void btn_Ejercicio3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio3MouseExited
        if((btn_prin.getBackground().getRGB() == -15374912 || btn_Ejercicio1.getBackground().getRGB() == -15374912
           || btn_Ejercicio2.getBackground().getRGB() == -15374912
           || btn_Espacios.getBackground().getRGB() == -15374912 || btn_Ejercicio5.getBackground().getRGB() == -15374912
           || btn_Ejercicio6.getBackground().getRGB() == -15374912) && btn_Ejercicio2.getBackground().getRGB() != -6710887)
           {
            resetColor(btn_Ejercicio3);
           }
    }//GEN-LAST:event_btn_Ejercicio3MouseExited

    private void btn_EspaciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EspaciosMouseEntered
        if(btn_Espacios.getBackground().getRGB() == -15574355)
            setColor(btn_Espacios);
    }//GEN-LAST:event_btn_EspaciosMouseEntered

    private void btn_EspaciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EspaciosMouseExited
        if((btn_prin.getBackground().getRGB() == -15374912 || btn_Ejercicio1.getBackground().getRGB() == -15374912
           || btn_Ejercicio2.getBackground().getRGB() == -15374912 || btn_Ejercicio3.getBackground().getRGB() == -15374912
           || btn_Ejercicio5.getBackground().getRGB() == -15374912
           || btn_Ejercicio6.getBackground().getRGB() == -15374912) && btn_Ejercicio2.getBackground().getRGB() != -6710887)
           {
            resetColor(btn_Espacios);
           }
    }//GEN-LAST:event_btn_EspaciosMouseExited

    private void red_squrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_red_squrMouseEntered

    private void red_squrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMouseExited
        red_squr.setBackground(new Color(0,75,50));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_red_squrMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        red_squr.setBackground(new Color(0,75,50));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseExited

    private void btn_Ejercicio5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio5MouseEntered
        if(btn_Ejercicio5.getBackground().getRGB() == -15574355)
            setColor(btn_Ejercicio5);
    }//GEN-LAST:event_btn_Ejercicio5MouseEntered

    private void btn_Ejercicio5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio5MouseExited
        if((btn_prin.getBackground().getRGB() == -15374912 || btn_Ejercicio1.getBackground().getRGB() == -15374912
           || btn_Ejercicio2.getBackground().getRGB() == -15374912 || btn_Ejercicio3.getBackground().getRGB() == -15374912
           || btn_Espacios.getBackground().getRGB() == -15374912 
           || btn_Ejercicio6.getBackground().getRGB() == -15374912) && btn_Ejercicio2.getBackground().getRGB() != -6710887)
           {
                resetColor(btn_Ejercicio5);
           }
    }//GEN-LAST:event_btn_Ejercicio5MouseExited
//Funcion de el boton sacudida
    private void btn_Ejercicio5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio5MousePressed

        resetColor(btn_prin);
        resetColor(btn_Ejercicio1);
        resetColor(btn_Ejercicio2);
        resetColor(btn_Ejercicio3);
        resetColor(btn_Espacios);
        setColor(btn_Ejercicio5);
        resetColor(btn_Ejercicio6);

        // Abrir sección
        Anual p1 = new Anual();
        p1.setSize(750, 430);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
       
    }//GEN-LAST:event_btn_Ejercicio5MousePressed

    private void btn_Ejercicio6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio6MouseEntered
        if(btn_Ejercicio6.getBackground().getRGB() == -15574355)
            setColor(btn_Ejercicio6);
    }//GEN-LAST:event_btn_Ejercicio6MouseEntered

    private void btn_Ejercicio6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio6MouseExited
        if((btn_prin.getBackground().getRGB() == -15374912 || btn_Ejercicio1.getBackground().getRGB() == -15374912
           || btn_Ejercicio2.getBackground().getRGB() == -15374912 || btn_Ejercicio3.getBackground().getRGB() == -15374912
           || btn_Espacios.getBackground().getRGB() == -15374912 || btn_Ejercicio5.getBackground().getRGB() == -15374912)
           && btn_Ejercicio2.getBackground().getRGB() != -6710887)
        {
            resetColor(btn_Ejercicio6);
        }
            
    }//GEN-LAST:event_btn_Ejercicio6MouseExited
//Funcion del boton baraja
    private void btn_Ejercicio6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Ejercicio6MousePressed
     
        resetColor(btn_prin);
        resetColor(btn_Ejercicio1);
        resetColor(btn_Ejercicio2);
        resetColor(btn_Ejercicio3);
        resetColor(btn_Espacios);
        resetColor(btn_Ejercicio5);
        setColor(btn_Ejercicio6);

        // Abrir sección
        ULAM p1 = new ULAM();
        p1.setSize(750, 430);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }//GEN-LAST:event_btn_Ejercicio6MousePressed

    private void Activar_color(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Activar_color

    }//GEN-LAST:event_Activar_color

    private void RegresarpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarpMousePressed
        dispose();
        new Principal().setVisible(true);
    }//GEN-LAST:event_RegresarpMousePressed

    private void RegresarpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarpMouseEntered
        Regresarp.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_RegresarpMouseEntered

    private void RegresarpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarpMouseExited
        Regresarp.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_RegresarpMouseExited

//Funciones para volver a Poner y quitar el color de los botones
    void setColor(JPanel panel){
        panel.setBackground(new Color(0,51,0));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(51,51,51));
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Regresarp;
    private javax.swing.JPanel Title;
    private javax.swing.JLabel app_name;
    private javax.swing.JPanel btn_Ejercicio1;
    private javax.swing.JPanel btn_Ejercicio2;
    private javax.swing.JPanel btn_Ejercicio3;
    private javax.swing.JPanel btn_Ejercicio5;
    private javax.swing.JPanel btn_Ejercicio6;
    private javax.swing.JPanel btn_Espacios;
    private javax.swing.JPanel btn_prin;
    public static javax.swing.JPanel content;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel red_squr;
    private javax.swing.JLabel slogan;
    // End of variables declaration//GEN-END:variables
}
