/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab3;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Antonio
 */
public class Espacios extends javax.swing.JPanel {

    
    public Espacios() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Text1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        txtFrase = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtEspacios = new javax.swing.JTextField();
        Text2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setForeground(new java.awt.Color(0, 0, 0));
        Text1.setText("Numero de Espacios:");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 75, 50));
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 180, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 10, 300));

        button.setBackground(new java.awt.Color(0, 75, 50));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contar");
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 110, 30));

        Title1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(0, 0, 0));
        Title1.setText("Contador de Espacios");
        add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        txtFrase.setForeground(new java.awt.Color(102, 102, 102));
        txtFrase.setBorder(null);
        txtFrase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFraseMousePressed(evt);
            }
        });
        txtFrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFraseActionPerformed(evt);
            }
        });
        txtFrase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFraseKeyTyped(evt);
            }
        });
        add(txtFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 180, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 220, 10));

        txtEspacios.setForeground(new java.awt.Color(102, 102, 102));
        txtEspacios.setText("No se a contado nada");
        txtEspacios.setBorder(null);
        txtEspacios.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEspacios.setEnabled(false);
        txtEspacios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEspaciosMousePressed(evt);
            }
        });
        txtEspacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspaciosActionPerformed(evt);
            }
        });
        txtEspacios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEspaciosKeyTyped(evt);
            }
        });
        add(txtEspacios, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 220, 20));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setForeground(new java.awt.Color(0, 0, 0));
        Text2.setText("Frase:");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFraseActionPerformed
        
    }//GEN-LAST:event_txtFraseActionPerformed

    private void txtFraseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFraseMousePressed
        
    }//GEN-LAST:event_txtFraseMousePressed

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        setColor(button);
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        resetColor(button);
    }//GEN-LAST:event_buttonMouseExited
    // DEVOLVER
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        //jLabel1.setText(String.valueOf(arreglo.tamaño_arreglo()));
        String valor =  txtFrase.getText();
        String pala = null;
        int lon = valor.length();
        int i=0, cont= 0, result = 0;
        
        result = palabra(valor,lon,i,cont,pala);
        
        if(!(valor.equals("")))
            txtEspacios.setText("La Oracion tinen "+String.valueOf(result)+ " espacios en blanco");
    }//GEN-LAST:event_buttonMousePressed

    private void txtFraseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFraseKeyTyped
        
    }//GEN-LAST:event_txtFraseKeyTyped

    private void txtEspaciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEspaciosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspaciosMousePressed

    private void txtEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspaciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspaciosActionPerformed

    private void txtEspaciosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspaciosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspaciosKeyTyped

    //colores
    void setColor(JPanel panel){
        panel.setBackground(new Color(0,51,0));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(0,75,50));
    }
    
    public static int palabra(String pa, int lon,int i, int cont, String pala)
    {
            if (i<lon)
            {
                    pala = pa.substring(i, i+1);
                    if (pala.compareTo(" ")==0)
                    {
                            cont++;
                    }
                    return palabra(pa,lon,i+1,cont,pala);
            }
            return cont;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Title1;
    private javax.swing.JPanel body;
    private javax.swing.JPanel button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtEspacios;
    private javax.swing.JTextField txtFrase;
    // End of variables declaration//GEN-END:variables
}
