/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab3;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Antonio
 */
public class ULAM extends javax.swing.JPanel {
    
    public ULAM() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_Mensaje = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSpinner2 = new javax.swing.JSpinner();
        Text1 = new javax.swing.JLabel();
        button_Añadir = new javax.swing.JPanel();
        Lb_TextAñadir = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title1.setText("Secuencia ULAM");
        add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        txtArea_Mensaje.setColumns(20);
        txtArea_Mensaje.setRows(5);
        txtArea_Mensaje.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtArea_Mensaje.setEnabled(false);
        jScrollPane1.setViewportView(txtArea_Mensaje);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 430, 110));

        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 260, 10));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 260, -1));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setText("Añadir numero");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        button_Añadir.setBackground(new java.awt.Color(18, 90, 173));
        button_Añadir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button_Añadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_AñadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_AñadirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_AñadirMousePressed(evt);
            }
        });
        button_Añadir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lb_TextAñadir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Lb_TextAñadir.setForeground(new java.awt.Color(255, 255, 255));
        Lb_TextAñadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_TextAñadir.setText("Correr ULAM");
        button_Añadir.add(Lb_TextAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        add(button_Añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 260, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void button_AñadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_AñadirMouseEntered
        setColor(button_Añadir);
    }//GEN-LAST:event_button_AñadirMouseEntered

    private void button_AñadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_AñadirMouseExited
        resetColor(button_Añadir);
    }//GEN-LAST:event_button_AñadirMouseExited

    private void button_AñadirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_AñadirMousePressed
        int valor = (int) jSpinner2.getValue();
        
        if(valor > 0)
        {
            StringBuilder MessageBuilder = new StringBuilder();
            MessageBuilder.append("Secuencia ULAM:\n");
            int prueba;
            prueba = ULAM(valor,MessageBuilder);
            txtArea_Mensaje.setText(MessageBuilder.toString());
        }
       
    }//GEN-LAST:event_button_AñadirMousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    public static int ULAM(int n, StringBuilder Mensaje)
    {
        Mensaje.append(String.valueOf(n)+"  ");
        if (n == 1)
        {
                return 1;
        }
        else if (n%2 == 0) 
        {
                n =  ULAM(n/2, Mensaje);
                return n;
        }
        else
        {
                n = ULAM(n*3+1, Mensaje);
                return n;
        }	
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lb_TextAñadir;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Title1;
    private javax.swing.JPanel body;
    private javax.swing.JPanel button_Añadir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea txtArea_Mensaje;
    // End of variables declaration//GEN-END:variables
}
