/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Lab2.Formularios.Laboratorio2;
import Lab3.Lab3;
import java.awt.Color;
import lab1grafico.Laboratorio1;

/**
 *
 * @author Thebeast
 */
public class Menu extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Title = new javax.swing.JPanel();
        red_squr = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_Lab2 = new javax.swing.JButton();
        btn_lab1 = new javax.swing.JButton();
        btn_Regresar = new javax.swing.JButton();
        btn_Lab3 = new javax.swing.JButton();
        btn_Lab4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 230));
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(51, 51, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleMouseDragged(evt);
            }
        });
        Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitleMousePressed(evt);
            }
        });

        red_squr.setBackground(new java.awt.Color(255, 255, 255));
        red_squr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        red_squr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                red_squrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                red_squrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                red_squrMousePressed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(102, 102, 102));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout red_squrLayout = new javax.swing.GroupLayout(red_squr);
        red_squr.setLayout(red_squrLayout);
        red_squrLayout.setHorizontalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        red_squrLayout.setVerticalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(red_squrLayout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleLayout.createSequentialGroup()
                .addGap(0, 274, Short.MAX_VALUE)
                .addComponent(red_squr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(red_squr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 20));

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Menu de Laboratorios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 70));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Lab2.setBackground(new java.awt.Color(204, 204, 255));
        btn_Lab2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_Lab2.setForeground(new java.awt.Color(0, 0, 153));
        btn_Lab2.setText("Laboratorio 2");
        btn_Lab2.setBorderPainted(false);
        btn_Lab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Lab2MousePressed(evt);
            }
        });
        jPanel2.add(btn_Lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 50));

        btn_lab1.setBackground(new java.awt.Color(204, 204, 255));
        btn_lab1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_lab1.setForeground(new java.awt.Color(0, 0, 153));
        btn_lab1.setText("Laboratorio 1");
        btn_lab1.setBorderPainted(false);
        btn_lab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_lab1MousePressed(evt);
            }
        });
        jPanel2.add(btn_lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 50));

        btn_Regresar.setBackground(new java.awt.Color(204, 204, 255));
        btn_Regresar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_Regresar.setForeground(new java.awt.Color(0, 0, 102));
        btn_Regresar.setText("Regresar");
        btn_Regresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Regresar.setBorderPainted(false);
        btn_Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_RegresarMousePressed(evt);
            }
        });
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 310, 50));

        btn_Lab3.setBackground(new java.awt.Color(204, 204, 255));
        btn_Lab3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_Lab3.setForeground(new java.awt.Color(0, 0, 153));
        btn_Lab3.setText("Laboratorio 3");
        btn_Lab3.setBorderPainted(false);
        btn_Lab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Lab3MousePressed(evt);
            }
        });
        jPanel2.add(btn_Lab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 310, 50));

        btn_Lab4.setBackground(new java.awt.Color(204, 204, 255));
        btn_Lab4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btn_Lab4.setForeground(new java.awt.Color(0, 0, 153));
        btn_Lab4.setText("Laboratorio 4");
        btn_Lab4.setBorderPainted(false);
        btn_Lab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Lab4MousePressed(evt);
            }
        });
        jPanel2.add(btn_Lab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 310, 50));

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 310, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        red_squr.setBackground(new Color(255,255,255));
        exit.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_exitMouseExited

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void red_squrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_red_squrMouseEntered

    private void red_squrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMouseExited
        red_squr.setBackground(new Color(255,255,255));
        exit.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_red_squrMouseExited

    private void red_squrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMousePressed
        System.exit(0);
    }//GEN-LAST:event_red_squrMousePressed

    private void TitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_TitleMouseDragged

    private void TitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_TitleMousePressed

    private void btn_RegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegresarMousePressed
        dispose();
        new Presentacion().setVisible(true);
    }//GEN-LAST:event_btn_RegresarMousePressed

    private void btn_Lab2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Lab2MousePressed
        dispose();
        new Laboratorio2().setVisible(true);
    }//GEN-LAST:event_btn_Lab2MousePressed

    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RegresarActionPerformed

    private void btn_Lab3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Lab3MousePressed
        dispose();
        new Lab3().setVisible(true);
    }//GEN-LAST:event_btn_Lab3MousePressed

    private void btn_lab1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lab1MousePressed
        dispose();
        new Laboratorio1().setVisible(true);
    }//GEN-LAST:event_btn_lab1MousePressed

    private void btn_Lab4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Lab4MousePressed
        dispose();
        new Lab4.Laboratorio4().setVisible(true);
    }//GEN-LAST:event_btn_Lab4MousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Title;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_Lab2;
    private javax.swing.JButton btn_Lab3;
    private javax.swing.JButton btn_Lab4;
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JButton btn_lab1;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel red_squr;
    // End of variables declaration//GEN-END:variables
}
