/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab1grafico;

import Principal.Principal;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Thebeast
 */
public class MarcoEj6 extends javax.swing.JFrame {

    /**
     * Creates new form MarcoEj1
     */
    public MarcoEj6() {
        initComponents();
        this.setLocationRelativeTo(null);
        int tam = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el tamaño del arreglo"));
        int opc, n=-1;
        String nombre[]= new String[tam], apellido[]= new String[tam], semestre[]= new String[tam], cali[]= new String[tam];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IngresarN = new javax.swing.JButton();
        Nuevo = new javax.swing.JButton();
        EliminarAlumno = new javax.swing.JButton();
        MostrarAlumno2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(13, 71, 161));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("_________________");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("EJERCICIO 6");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, -1));

        IngresarN.setBackground(new java.awt.Color(0, 51, 153));
        IngresarN.setText("Nuevo Vendedor");
        IngresarN.setBorder(null);
        IngresarN.setBorderPainted(false);
        IngresarN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IngresarNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IngresarNMouseExited(evt);
            }
        });
        jPanel2.add(IngresarN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 190, 40));

        Nuevo.setBackground(new java.awt.Color(0, 51, 153));
        Nuevo.setText("Modificar numero de ventas de Vendedor");
        Nuevo.setBorder(null);
        Nuevo.setBorderPainted(false);
        Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NuevoMouseExited(evt);
            }
        });
        jPanel2.add(Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 190, 40));

        EliminarAlumno.setBackground(new java.awt.Color(0, 51, 153));
        EliminarAlumno.setText("Informacion de un Vendedor");
        EliminarAlumno.setBorder(null);
        EliminarAlumno.setBorderPainted(false);
        EliminarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EliminarAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarAlumnoMouseExited(evt);
            }
        });
        jPanel2.add(EliminarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 190, 40));

        MostrarAlumno2.setBackground(new java.awt.Color(51, 0, 0));
        MostrarAlumno2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MostrarAlumno2.setText("Regresar");
        MostrarAlumno2.setBorder(null);
        MostrarAlumno2.setBorderPainted(false);
        MostrarAlumno2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MostrarAlumno2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MostrarAlumno2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MostrarAlumno2MousePressed(evt);
            }
        });
        jPanel2.add(MostrarAlumno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 190, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 580));

        jPanel3.setBackground(new java.awt.Color(25, 118, 210));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Metodos para insertar y ordenar");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 580, 110));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Facultad de Electrotecnia y Computación (F.E.C)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarNMouseEntered
        IngresarN.setBackground(new Color(25,118,210));
    }//GEN-LAST:event_IngresarNMouseEntered

    private void IngresarNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarNMouseExited
        IngresarN.setBackground(new Color(0,51,153));
    }//GEN-LAST:event_IngresarNMouseExited

    private void NuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoMouseEntered

    private void NuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoMouseExited

    private void EliminarAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarAlumnoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarAlumnoMouseEntered

    private void EliminarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarAlumnoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarAlumnoMouseExited

    private void MostrarAlumno2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarAlumno2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarAlumno2MouseEntered

    private void MostrarAlumno2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarAlumno2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarAlumno2MouseExited

    private void MostrarAlumno2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarAlumno2MousePressed
        dispose();
        new Principal().setVisible(true);
    }//GEN-LAST:event_MostrarAlumno2MousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarAlumno;
    private javax.swing.JButton IngresarN;
    private javax.swing.JButton MostrarAlumno2;
    private javax.swing.JButton Nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
