/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab1grafico;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.*;
import lab1grafico.Menu_de_Ejercicios;

/**
 *
 * @author Thebeast
 */
public class MarcoEj2 extends javax.swing.JFrame {

    /**
     * Creates new form MarcoEj1
     */
    public MarcoEj2() {
        initComponents();
        this.setLocationRelativeTo(null);
        int tam = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el tamaño del arreglo"));
        int opc, n=-1;
        String nombre[]= new String[tam], apellido[]= new String[tam], semestre[]= new String[tam], cali[]= new String[tam];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nuevocl = new javax.swing.JButton();
        modificarmoroso = new javax.swing.JButton();
        Eliminarcliente = new javax.swing.JButton();
        infocl = new javax.swing.JButton();
        mostrarcl = new javax.swing.JButton();
        MostrarAlumno2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(13, 71, 161));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("_________________");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("EJERCICIO 2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, -1));

        nuevocl.setBackground(new java.awt.Color(0, 51, 153));
        nuevocl.setText("Nuevo Cliente");
        nuevocl.setBorder(null);
        nuevocl.setBorderPainted(false);
        nuevocl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevoclMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevoclMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nuevoclMousePressed(evt);
            }
        });
        jPanel2.add(nuevocl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 190, 40));

        modificarmoroso.setBackground(new java.awt.Color(0, 51, 153));
        modificarmoroso.setText("Modificar estado de moroso");
        modificarmoroso.setBorder(null);
        modificarmoroso.setBorderPainted(false);
        modificarmoroso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarmorosoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarmorosoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificarmorosoMousePressed(evt);
            }
        });
        jPanel2.add(modificarmoroso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 190, 40));

        Eliminarcliente.setBackground(new java.awt.Color(0, 51, 153));
        Eliminarcliente.setText("Eliminar Cliente");
        Eliminarcliente.setBorder(null);
        Eliminarcliente.setBorderPainted(false);
        Eliminarcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EliminarclienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarclienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EliminarclienteMousePressed(evt);
            }
        });
        jPanel2.add(Eliminarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 190, 40));

        infocl.setBackground(new java.awt.Color(0, 51, 153));
        infocl.setText("Informacion de un Cliente");
        infocl.setBorder(null);
        infocl.setBorderPainted(false);
        infocl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoclMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoclMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                infoclMousePressed(evt);
            }
        });
        jPanel2.add(infocl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 190, 40));

        mostrarcl.setBackground(new java.awt.Color(0, 51, 153));
        mostrarcl.setText("Mostrar todos los clientes");
        mostrarcl.setBorder(null);
        mostrarcl.setBorderPainted(false);
        mostrarcl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarclMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarclMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mostrarclMousePressed(evt);
            }
        });
        jPanel2.add(mostrarcl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 190, 40));

        MostrarAlumno2.setBackground(new java.awt.Color(51, 0, 0));
        MostrarAlumno2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MostrarAlumno2.setText("Regresar");
        MostrarAlumno2.setBorder(null);
        MostrarAlumno2.setBorderPainted(false);
        MostrarAlumno2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MostrarAlumno2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MostrarAlumno2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MostrarAlumno2MousePressed(evt);
            }
        });
        jPanel2.add(MostrarAlumno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 190, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 580));

        jPanel3.setBackground(new java.awt.Color(25, 118, 210));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Metodos para insertar y ordenar");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 580, 110));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Facultad de Electrotecnia y Computación (F.E.C)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        Content.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 580, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoclMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoclMouseEntered
        nuevocl.setBackground(new Color(25,118,210));
    }//GEN-LAST:event_nuevoclMouseEntered

    private void nuevoclMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoclMouseExited
        nuevocl.setBackground(new Color(0,51,153));
    }//GEN-LAST:event_nuevoclMouseExited

    private void modificarmorosoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarmorosoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarmorosoMouseEntered

    private void modificarmorosoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarmorosoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarmorosoMouseExited

    private void EliminarclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarclienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarclienteMouseEntered

    private void EliminarclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarclienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarclienteMouseExited

    private void infoclMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoclMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_infoclMouseEntered

    private void infoclMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoclMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_infoclMouseExited

    private void mostrarclMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarclMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarclMouseEntered

    private void mostrarclMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarclMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarclMouseExited

    private void MostrarAlumno2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarAlumno2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarAlumno2MouseEntered

    private void MostrarAlumno2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarAlumno2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarAlumno2MouseExited

    private void MostrarAlumno2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarAlumno2MousePressed
        dispose();
        new Menu_de_Ejercicios().setVisible(true);
    }//GEN-LAST:event_MostrarAlumno2MousePressed

    private void nuevoclMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoclMousePressed
            nuevocl p1 = new nuevocl();
            p1.setSize(580, 400);
            p1.setLocation(0,0);
            
            Content.removeAll();
            Content.add(p1, BorderLayout.CENTER);
            Content.revalidate();
            Content.repaint();
    }//GEN-LAST:event_nuevoclMousePressed

    private void modificarmorosoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarmorosoMousePressed
            modificarcl p2 = new modificarcl();
            p2.setSize(580, 400);
            p2.setLocation(0,0);
            
            Content.removeAll();
            Content.add(p2, BorderLayout.CENTER);
            Content.revalidate();
            Content.repaint();
    }//GEN-LAST:event_modificarmorosoMousePressed

    private void EliminarclienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarclienteMousePressed
            eliminarcl p3 = new eliminarcl();
            p3.setSize(580, 400);
            p3.setLocation(0,0);
            
            Content.removeAll();
            Content.add(p3, BorderLayout.CENTER);
            Content.revalidate();
            Content.repaint();
    }//GEN-LAST:event_EliminarclienteMousePressed

    private void infoclMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoclMousePressed
            Infocl p4 = new Infocl();
            p4.setSize(580, 400);
            p4.setLocation(0,0);
            
            Content.removeAll();
            Content.add(p4, BorderLayout.CENTER);
            Content.revalidate();
            Content.repaint();
    }//GEN-LAST:event_infoclMousePressed

    private void mostrarclMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarclMousePressed
            Mostrarcl p5 = new Mostrarcl();
            p5.setSize(580, 400);
            p5.setLocation(0,0);
            
            Content.removeAll();
            Content.add(p5, BorderLayout.CENTER);
            Content.revalidate();
            Content.repaint();
    }//GEN-LAST:event_mostrarclMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JButton Eliminarcliente;
    private javax.swing.JButton MostrarAlumno2;
    private javax.swing.JButton infocl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton modificarmoroso;
    private javax.swing.JButton mostrarcl;
    private javax.swing.JButton nuevocl;
    // End of variables declaration//GEN-END:variables
}
