/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab1grafico;

import Principal.Principal;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thebeast
 */
public class MarcoEj6 extends javax.swing.JFrame {
int tam = 15;
int n = -1, Cam = 0;
String nombre[] = new String[tam];
String Apellido[] = new String[tam];
int ventas[] = new int[tam]; 
DefaultTableModel modelo = new DefaultTableModel(); 
    /**
     * Creates new form MarcoEj1
     */
    public MarcoEj6() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Ventas");
        Tabla1.setModel(modelo);
        Mostrar1.setVisible(false);
        Cambiar.setVisible(false);
        NuevoEmpleado.setVisible(true);
        Desabilitado1.setVisible(false);
        VentasCambiar.setVisible(false);
        Actualizar.setVisible(false);
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," Septiembre"
            ,"Octubre","Noviembre","Diciemrbre"};
        fecha.setText("Hoy es "+dia+" de "+meses[month - 1]+" de "+year);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        red_squr = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Regresar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        IngresarEmpleado = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        EstadoCliente = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        MostrarCliente = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();
        NuevoEmpleado = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ApellidoAñadir = new javax.swing.JTextField();
        NombreAñadir = new javax.swing.JTextField();
        VentasAñadir = new javax.swing.JTextField();
        AñadirBoton = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Cambiar = new javax.swing.JPanel();
        Desabilitado1 = new javax.swing.JLabel();
        NombreModificar = new javax.swing.JTextField();
        Actualizar = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        BuscarModificarButon1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        VentasCambiar = new javax.swing.JTextField();
        Mostrar1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        NombreMostrar = new javax.swing.JTextField();
        MostrarInfo = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Metodos para insertar y ordenar");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        fecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(0, 0, 0));
        fecha.setText("Hoy es Sábado 28 de Abril de 2018");
        jPanel3.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 590, 110));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Facultad de Electrotecnia y Computación (F.E.C)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 75, 50));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        red_squr.setBackground(new java.awt.Color(0, 75, 50));
        red_squr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        red_squr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                red_squrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                red_squrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                red_squrMousePressed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(0, 75, 50));
        exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout red_squrLayout = new javax.swing.GroupLayout(red_squr);
        red_squr.setLayout(red_squrLayout);
        red_squrLayout.setHorizontalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(red_squrLayout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        red_squrLayout.setVerticalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(red_squrLayout.createSequentialGroup()
                .addComponent(exit)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel4.add(red_squr, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 0, 40, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 590, 70));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 51, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("_________________");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EJERCICIO 6");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 70));

        Regresar.setBackground(new java.awt.Color(51, 51, 51));
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegresarMousePressed(evt);
            }
        });
        Regresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Regresar");
        Regresar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel2.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 190, 40));

        IngresarEmpleado.setBackground(new java.awt.Color(51, 51, 51));
        IngresarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IngresarEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IngresarEmpleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngresarEmpleadoMousePressed(evt);
            }
        });
        IngresarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingresar Vendedor");
        IngresarEmpleado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(IngresarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 40));

        EstadoCliente.setBackground(new java.awt.Color(51, 51, 51));
        EstadoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EstadoClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EstadoClienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EstadoClienteMousePressed(evt);
            }
        });
        EstadoCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cambiar Ventas");
        EstadoCliente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.add(EstadoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, 40));

        MostrarCliente.setBackground(new java.awt.Color(51, 51, 51));
        MostrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MostrarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MostrarClienteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MostrarClienteMousePressed(evt);
            }
        });
        MostrarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mostrar Vendedor");
        MostrarCliente.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(MostrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 190, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 580));

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NuevoEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        NuevoEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        NuevoEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nuevo Vendedor");
        NuevoEmpleado.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nombre");
        NuevoEmpleado.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Apellido");
        NuevoEmpleado.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Ventas");
        NuevoEmpleado.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        ApellidoAñadir.setBackground(new java.awt.Color(51, 51, 51));
        ApellidoAñadir.setForeground(new java.awt.Color(255, 255, 255));
        NuevoEmpleado.add(ApellidoAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 90, -1));

        NombreAñadir.setBackground(new java.awt.Color(51, 51, 51));
        NombreAñadir.setForeground(new java.awt.Color(255, 255, 255));
        NuevoEmpleado.add(NombreAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, -1));

        VentasAñadir.setBackground(new java.awt.Color(51, 51, 51));
        VentasAñadir.setForeground(new java.awt.Color(255, 255, 255));
        VentasAñadir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VentasAñadirKeyTyped(evt);
            }
        });
        NuevoEmpleado.add(VentasAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 90, -1));

        AñadirBoton.setBackground(new java.awt.Color(0, 51, 0));
        AñadirBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AñadirBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AñadirBotonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AñadirBotonMousePressed(evt);
            }
        });
        AñadirBoton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Añadir");
        AñadirBoton.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        NuevoEmpleado.add(AñadirBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 140, 40));

        Content.add(NuevoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 530, 330));

        Cambiar.setBackground(new java.awt.Color(255, 255, 255));
        Cambiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Desabilitado1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Desabilitado1.setForeground(new java.awt.Color(0, 0, 0));
        Desabilitado1.setText("Ventas");
        Cambiar.add(Desabilitado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        NombreModificar.setBackground(new java.awt.Color(51, 51, 51));
        NombreModificar.setForeground(new java.awt.Color(255, 255, 255));
        Cambiar.add(NombreModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, -1));

        Actualizar.setBackground(new java.awt.Color(0, 51, 0));
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActualizarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ActualizarMousePressed(evt);
            }
        });
        Actualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Actualizar");
        Actualizar.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        Cambiar.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 110, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Nombre del Vendedor a Modificar");
        Cambiar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        BuscarModificarButon1.setBackground(new java.awt.Color(0, 51, 0));
        BuscarModificarButon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BuscarModificarButon1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuscarModificarButon1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarModificarButon1MousePressed(evt);
            }
        });
        BuscarModificarButon1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Buscar");
        BuscarModificarButon1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        Cambiar.add(BuscarModificarButon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 110, 30));

        VentasCambiar.setBackground(new java.awt.Color(51, 51, 51));
        VentasCambiar.setForeground(new java.awt.Color(255, 255, 255));
        VentasCambiar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VentasCambiarKeyTyped(evt);
            }
        });
        Cambiar.add(VentasCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 110, -1));

        Content.add(Cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 500, 310));

        Mostrar1.setBackground(new java.awt.Color(255, 255, 255));
        Mostrar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Nombre del Empleado a Mostrar");
        Mostrar1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        NombreMostrar.setBackground(new java.awt.Color(51, 51, 51));
        NombreMostrar.setForeground(new java.awt.Color(255, 255, 255));
        Mostrar1.add(NombreMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 130, -1));

        MostrarInfo.setBackground(new java.awt.Color(0, 51, 0));
        MostrarInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MostrarInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MostrarInfoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MostrarInfoMousePressed(evt);
            }
        });
        MostrarInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Mostrar");
        MostrarInfo.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        Mostrar1.add(MostrarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 120, 30));

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla1);

        Mostrar1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 370, 210));

        Content.add(Mostrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 530, 350));

        jPanel1.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 590, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarEmpleadoMouseEntered
        IngresarEmpleado.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_IngresarEmpleadoMouseEntered

    private void IngresarEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarEmpleadoMouseExited
        IngresarEmpleado.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_IngresarEmpleadoMouseExited

    private void EstadoClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadoClienteMouseEntered
        EstadoCliente.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_EstadoClienteMouseEntered

    private void EstadoClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadoClienteMouseExited
        EstadoCliente.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_EstadoClienteMouseExited

    private void MostrarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarClienteMouseEntered
        MostrarCliente.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_MostrarClienteMouseEntered

    private void MostrarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarClienteMouseExited
        MostrarCliente.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_MostrarClienteMouseExited

    private void RegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseEntered
        Regresar.setBackground(new Color(168,23,25));
    }//GEN-LAST:event_RegresarMouseEntered

    private void RegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseExited
        Regresar.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_RegresarMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        red_squr.setBackground(new Color(0,75,50));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseExited

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void red_squrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_red_squrMouseEntered

    private void red_squrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMouseExited
        red_squr.setBackground(new Color(0,75,50));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_red_squrMouseExited

    private void red_squrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_squrMousePressed
        System.exit(0);
    }//GEN-LAST:event_red_squrMousePressed

    private void IngresarEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarEmpleadoMousePressed
        Mostrar1.setVisible(false);
        Cambiar.setVisible(false);
        NuevoEmpleado.setVisible(true);
        Desabilitado1.setVisible(false);
        VentasCambiar.setVisible(false);
        Actualizar.setVisible(false);
    }//GEN-LAST:event_IngresarEmpleadoMousePressed

    private void EstadoClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadoClienteMousePressed
        Mostrar1.setVisible(false);
        Cambiar.setVisible(true);
        NuevoEmpleado.setVisible(false);
        Desabilitado1.setVisible(false);
        VentasCambiar.setVisible(false);
        Actualizar.setVisible(false);
    }//GEN-LAST:event_EstadoClienteMousePressed

    private void MostrarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarClienteMousePressed
        Mostrar1.setVisible(true);
        Cambiar.setVisible(false);
        NuevoEmpleado.setVisible(false);
        Desabilitado1.setVisible(false);
        VentasCambiar.setVisible(false);
        Actualizar.setVisible(false);
        for (int i = 0; i < Tabla1.getRowCount(); i++) 
        {
        modelo.removeRow(i);
        i-=1;
        }
    }//GEN-LAST:event_MostrarClienteMousePressed

    private void RegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMousePressed
        dispose();
        new Principal().setVisible(true);
    }//GEN-LAST:event_RegresarMousePressed
    public static int Busca(String nom[], String nomB,int n){
 		int i = 0;

 		while ((i <= n) && (nom[i].compareTo(nomB)< 0)) /*Comprueba que no vaya primero*/
			i++;
 		
		if ((i > n) || (nom[i].compareTo(nomB)> 0)) /*Comprueba que vaya primero*/
			return (-i);
		else
			return (i);
    }
    private void AñadirBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirBotonMousePressed
        if (NombreAñadir.getText().equals("") || ApellidoAñadir.getText().equals("") || VentasAñadir.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Hay campos vacios");
        }
        else
        {
            if (n == -1){ /*Agrega al empleado en la posicion 0 cuando no hay datos*/
			n++;
			nombre[n] = NombreAñadir.getText();
                        Apellido[n] = ApellidoAñadir.getText();
			ventas[n]= Integer.parseInt(VentasAñadir.getText());
                        JOptionPane.showMessageDialog(null, "Insercion realizada.");
		}
		else if (n < (tam-1)){ /*Agrega al empleado cuando hay otro empleado existente*/
			String nomB= NombreAñadir.getText();
			
			int pos = Busca(nombre, nomB, n);
			
			if ((pos >= 0) && ((pos == 0) && (nomB.equalsIgnoreCase(nombre[0]))))
				JOptionPane.showMessageDialog(null, nomB + " ya existe.");
			else{
				n=n+1;
				pos= pos * (-1);
				
				for(int i=n; i>= (pos+1); i--){
					nombre[i]= nombre[i-1];
					ventas[i]= ventas[i-1];
				}
				
				nombre[pos] = nomB;
                                Apellido[pos] = ApellidoAñadir.getText();
                                ventas[pos]= Integer.parseInt(VentasAñadir.getText());
				
				JOptionPane.showMessageDialog(null, "Insercion realizada.");
			}
		}
		else
			JOptionPane.showMessageDialog(null, "No hay espacio disponible");
        }
    }//GEN-LAST:event_AñadirBotonMousePressed

    private void BuscarModificarButon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarModificarButon1MousePressed
     if (NombreModificar.getText().equals(""))
    {
        JOptionPane.showMessageDialog(null,"Hay campos vacios");
    }
    else
    {
        String nombreB = NombreModificar.getText();
        int i=0;
        for(i = 0; i<=n && !(nombreB.equalsIgnoreCase(nombre[i])); i++);

        if(i>n)
        {
            JOptionPane.showMessageDialog(null, nombreB+" no encontrado");
        }
        else
        {
            Cam = i;
            Desabilitado1.setVisible(true);
            VentasCambiar.setVisible(true);
            Actualizar.setVisible(true);
        }
    }
    }//GEN-LAST:event_BuscarModificarButon1MousePressed

    private void ActualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMousePressed
        if (VentasCambiar.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Hay campos vacios");
        }
        else
        {
            ventas[Cam]= Integer.parseInt(VentasCambiar.getText());
            JOptionPane.showMessageDialog(null,"Se modifico con exito");
        }
    }//GEN-LAST:event_ActualizarMousePressed

    private void MostrarInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarInfoMousePressed
         if (NombreMostrar.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Ingrese un nombre");
        }
        else
        {
            String nombreB = NombreMostrar.getText();
            int i=0;
            while((i<=n)&&(!(nombreB.equalsIgnoreCase(nombre[i])))){
                i++;
            }
            if(i>n)
            {
                JOptionPane.showMessageDialog(null, nombreB+" no encontrado");
            }
            else
            {
                Object [] datos = new Object[3];
                datos[0] = nombre[i];
                datos[1] = Apellido[i];
                datos[2] = ventas[i];
                modelo.addRow(datos);
            }
        }
    }//GEN-LAST:event_MostrarInfoMousePressed

    private void VentasCambiarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VentasCambiarKeyTyped
    int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
        
    if (!numeros)
    {
        evt.consume();
    }

    if (VentasCambiar.getText().trim().length() == 10) {
        evt.consume();
    }
    }//GEN-LAST:event_VentasCambiarKeyTyped

    private void VentasAñadirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VentasAñadirKeyTyped
    int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
        
    if (!numeros)
    {
        evt.consume();
    }

    if (VentasAñadir.getText().trim().length() == 10) {
        evt.consume();
    }
    }//GEN-LAST:event_VentasAñadirKeyTyped

    private void AñadirBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirBotonMouseEntered
        AñadirBoton.setBackground(new Color(0,75,50));
    }//GEN-LAST:event_AñadirBotonMouseEntered

    private void AñadirBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirBotonMouseExited
        AñadirBoton.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_AñadirBotonMouseExited

    private void ActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseEntered
        Actualizar.setBackground(new Color(0,75,50));
    }//GEN-LAST:event_ActualizarMouseEntered

    private void ActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseExited
        Actualizar.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_ActualizarMouseExited

    private void BuscarModificarButon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarModificarButon1MouseEntered
        BuscarModificarButon1.setBackground(new Color(0,75,50));
    }//GEN-LAST:event_BuscarModificarButon1MouseEntered

    private void BuscarModificarButon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarModificarButon1MouseExited
        BuscarModificarButon1.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_BuscarModificarButon1MouseExited

    private void MostrarInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarInfoMouseEntered
        MostrarInfo.setBackground(new Color(0,75,50));
    }//GEN-LAST:event_MostrarInfoMouseEntered

    private void MostrarInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarInfoMouseExited
        MostrarInfo.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_MostrarInfoMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actualizar;
    private javax.swing.JTextField ApellidoAñadir;
    private javax.swing.JPanel AñadirBoton;
    private javax.swing.JPanel BuscarModificarButon1;
    private javax.swing.JPanel Cambiar;
    private javax.swing.JPanel Content;
    private javax.swing.JLabel Desabilitado1;
    private javax.swing.JPanel EstadoCliente;
    private javax.swing.JPanel IngresarEmpleado;
    private javax.swing.JPanel Mostrar1;
    private javax.swing.JPanel MostrarCliente;
    private javax.swing.JPanel MostrarInfo;
    private javax.swing.JTextField NombreAñadir;
    private javax.swing.JTextField NombreModificar;
    private javax.swing.JTextField NombreMostrar;
    private javax.swing.JPanel NuevoEmpleado;
    private javax.swing.JPanel Regresar;
    private javax.swing.JTable Tabla1;
    private javax.swing.JTextField VentasAñadir;
    private javax.swing.JTextField VentasCambiar;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel red_squr;
    // End of variables declaration//GEN-END:variables
}
